### PR TITLE
integerated prisma and and updated some needed code

### PR DESCRIPTION
**Pull request by lokendra005**

### CODE REVIEW

**Review by divi2806 — COMMENTED** [review]
`import { z } from 'zod';

const PASSWORD_PATTERN = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/;

const UserRole = z.enum(['JOB_SEEKER', 'JOB_POSTER']);
type UserRole = z.infer<typeof UserRole>;

const jobSeekerFields = z.object({
  education: z.string().optional(),
  skills: z.array(z.string()).optional(),
  resumeUrl: z.string().url().optional(),
  portfolio: z.array(z.string().url()).optional(),
});

const jobPosterFields = z.object({
  company: z.string(),
  companyDescription: z.string(),
});

export const registerSchema = z.object({
  email: z.string().email(),
  password: z.string()
    .min(8)
    .regex(PASSWORD_PATTERN, 'Password must contain at least one uppercase letter, one lowercase letter, one number and one special character'),
  name: z.string().min(2),
  role: UserRole,
}).and(
  z.discriminatedUnion('role', [
    z.object({
      role: z.literal('JOB_SEEKER'),
      ...jobSeekerFields.shape,
    }),
    z.object({
      role: z.literal('JOB_POSTER'),
      ...jobPosterFields.shape,
    }),
  ])
);

export const loginSchema = z.object({
  email: z.string().email(),
  password: z.string(),
});

export const resetPasswordSchema = z.object({
  email: z.string().email(),
});

export const updatePasswordSchema = z.object({
  currentPassword: z.string(),
  newPassword: z.string()
    .min(8)
    .regex(PASSWORD_PATTERN, 'Password must contain at least one uppercase letter, one lowercase letter, one number and one special character'),
}).refine(
  data => data.currentPassword !== data.newPassword,
  { message: 'New password must be different from current password' }
);

export type RegisterDto = z.infer<typeof registerSchema>;
export type LoginDto = z.infer<typeof loginSchema>;
export type ResetPasswordDto = z.infer<typeof resetPasswordSchema>;
export type UpdatePasswordDto = z.infer<typeof updatePasswordSchema>;`

**Comment by divi2806** [comment]
double password field declaration? why?

**Comment by lokendra005** [comment]
one is for registering and another is for updating password.

________________________________

**Comment by lokendra005** [comment]
if you want we can make it reusable. But will have to think on that or you can also work on it

________________________________

**Pull request merged**
